# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/Uart_Exp/Uart_Exp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Exp || ORIG_REF_NAME==Uart_Exp} -quiet] -quiet

# IP: bd/Uart_Exp/ip/Uart_Exp_processing_system7_0_0/Uart_Exp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Exp_processing_system7_0_0 || ORIG_REF_NAME==Uart_Exp_processing_system7_0_0} -quiet] -quiet

# IP: bd/Uart_Exp/ip/Uart_Exp_axi_uartlite_0_0/Uart_Exp_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Exp_axi_uartlite_0_0 || ORIG_REF_NAME==Uart_Exp_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Uart_Exp/ip/Uart_Exp_xbar_0/Uart_Exp_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Exp_xbar_0 || ORIG_REF_NAME==Uart_Exp_xbar_0} -quiet] -quiet

# IP: bd/Uart_Exp/ip/Uart_Exp_auto_pc_0/Uart_Exp_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Exp_auto_pc_0 || ORIG_REF_NAME==Uart_Exp_auto_pc_0} -quiet] -quiet

# IP: bd/Uart_Exp/ip/Uart_Exp_ps7_0_axi_periph_0/Uart_Exp_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Exp_ps7_0_axi_periph_0 || ORIG_REF_NAME==Uart_Exp_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Uart_Exp/ip/Uart_Exp_rst_ps7_0_100M_0/Uart_Exp_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Exp_rst_ps7_0_100M_0 || ORIG_REF_NAME==Uart_Exp_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Uart_Exp/ip/Uart_Exp_axi_gpio_0_0/Uart_Exp_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Exp_axi_gpio_0_0 || ORIG_REF_NAME==Uart_Exp_axi_gpio_0_0} -quiet] -quiet

# XDC: bd/Uart_Exp/Uart_Exp_ooc.xdc
